### ISSUE TITLE
Uncaught TypeError: Cannot read property 'textContent' of undefined

### ISSUE THREAD

**Issue by cgpro** [heiseonline/shariff#252]
I included it with webpack. It happens with Version 1.26.2 only.

1.25.2 works fine.

`jquery-3.2.1.min.js:2 jQuery.Deferred exception: Cannot read property 'textContent' of undefined TypeError: Cannot read property 'textContent' of undefined
    at o.text (https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:13333)
    at e.title (https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:9125)
    at e.value (https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:10501)
    at e.value (https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:10560)
    at Object.e.exports [as twitter] (https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:33389)
    at https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:9719
    at Array.map (<anonymous>)
    at new e (https://cdnjs.cloudflare.com/ajax/libs/shariff/1.26.2/shariff.min.js:7:9692)
    at HTMLDocument.<anonymous> (http://localhost:8080/app.bundle.js?1406c4cbd579e96f7de1:50780:13)
    at j (https://code.jquery.com/jquery-3.2.1.min.js:2:29999) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
fire @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
ready @ jquery-3.2.1.min.js:2
S @ jquery-3.2.1.min.js:3
jquery-3.2.1.min.js:2 Uncaught TypeError: Cannot read property 'textContent' of undefined
    at o.text (shariff.min.js:7)
    at e.title (shariff.min.js:7)
    at e.value (shariff.min.js:7)
    at e.value (shariff.min.js:7)
    at Object.e.exports [as twitter] (shariff.min.js:7)
    at shariff.min.js:7
    at Array.map (<anonymous>)
    at new e (shariff.min.js:7)
    at HTMLDocument.<anonymous> (app.bundle.js?1406c4cbd579e96f7de1:50780)
    at j (jquery-3.2.1.min.js:2)`

**Comment by compeak** [comment]
Does this problem still occur in [v2.0.4](https://github.com/heiseonline/shariff/releases/tag/2.0.4)?
