### ISSUE TITLE
shariff plugin ojs issue

### ISSUE THREAD

**Issue by narendra2018** [heiseonline/shariff#374]
thrown in /home/petsdorg/public_html/aryan/1/plugins/generic/shariff/ShariffPlugin.inc.php on line 42
[18-May-2020 09:32:36 UTC] PHP Warning:  Declaration of ShariffSettingsForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in /home/petsdorg/public_html/aryan/1/plugins/generic/shariff/ShariffSettingsForm.inc.php on line 0
[18-May-2020 09:32:36 UTC] PHP Warning:  Declaration of ShariffSettingsForm::execute() should be compatible with Form::execute(...$functionArgs) in /home/petsdorg/public_html/aryan/1/plugins/generic/shariff/ShariffSettingsForm.inc.php on line 0
[18-May-2020 09:47:30 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/petsdorg/public_html/aryan/1/plugins/generic/shariff/ShariffPlugin.inc.php:42
Stack trace:
#0 /home/petsdorg/public_html/aryan/1/lib/pkp/classes/plugins/PluginRegistry.inc.php(69): ShariffPlugin->register('generic', 'plugins/generic...', NULL)
#1 /home/petsdorg/public_html/aryan/1/lib/pkp/classes/plugins/PluginRegistry.inc.php(144): PluginRegistry::register('generic', Object(ShariffPlugin), 'plugins/generic...', NULL)
#2 /home/petsdorg/public_html/aryan/1/lib/pkp/classes/core/Dispatcher.inc.php(132): PluginRegistry::loadCategory('generic', true)
#3 /home/petsdorg/public_html/aryan/1/lib/pkp/classes/core/PKPApplication.inc.php(278): Dispatcher->dispatch(Object(Request))
#4 /home/petsdorg/public_html/aryan/1/index.php(68): PKPApplication->execute()
#5 {main}
  thrown in /home/petsdorg/public_html/aryan/1/plugins/generic/shariff/ShariffPlugin.inc.php on line 42

**Comment by gerryfrancis** [comment]
@narendra2018 I guess this repository does not match your issue. Maybe it is better to close here and open a new issue in https://github.com/ojsde/shariff/issues .
